### PR TITLE
Tasks: change forkbomb to be more predictible

### PR DESCRIPTION
**Pull request by charlesvdv**

### CODE REVIEW

**Comment by charlesvdv** [comment]
I just push forced my branch because I had to change a little thing in my last commit (a remaining useless comment). I hope you didn't merge my branch locally ? :confused: @combefis

**Comment by combefis** [comment]
@charlesvdv I have not yet worked on this PR locally, so that's OK, don't worry!

**Comment by charlesvdv** [comment]
Great news ! :smile:

**Comment by combefis** [comment]
Merged! Thanks!

**Pull request merged**
